name = "LaMEM_C"
uuid = "29b6043d-3311-4c16-b469-b02bf85cb680"
authors = ["Anton Popov <popov@uni-mainz.de>", "Boris Kaus <kaus@uni-mainz.de>"]
version = "1.2.1"

[deps]
GeophysicalModelGenerator = "3700c31b-fa53-48a6-808a-ef22d5a84742"
LaMEM = "2e889f3d-35ce-4a77-8ea2-858aecb630f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
GeophysicalModelGenerator = "0.4"
LaMEM = "0.1.7"
julia = "1.6"